// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K8sapp
{
    [K8sappResourceType("k8sapp:index:ServiceDeployment")]
    public partial class ServiceDeployment : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Allocated IP address if applicable.
        /// </summary>
        [Output("ipAddress")]
        public Output<string?> IpAddress { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceDeployment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceDeployment(string name, ServiceDeploymentArgs args, ComponentResourceOptions? options = null)
            : base("k8sapp:index:ServiceDeployment", name, args ?? new ServiceDeploymentArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi-pequod/pequod-mlc-servicedeployment",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ServiceDeploymentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not to allocate an IP address for the service. Defaults to false.
        /// </summary>
        [Input("allocateIpAddress")]
        public Input<bool>? AllocateIpAddress { get; set; }

        /// <summary>
        /// Port container listens on.
        /// </summary>
        [Input("containerPort", required: true)]
        public Input<double> ContainerPort { get; set; } = null!;

        /// <summary>
        /// Name of the image for the application.
        /// </summary>
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        /// <summary>
        /// Used to indicate if minikube environment is being used. Defaults to False.
        /// </summary>
        [Input("isMinikube")]
        public Input<bool>? IsMinikube { get; set; }

        /// <summary>
        /// K8s namespace to use.
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// Number of pod replicas to create. Defaults to 1.
        /// </summary>
        [Input("replicas")]
        public Input<double>? Replicas { get; set; }

        /// <summary>
        /// Requested CPU. E.g. 250m means 0.25 CPU. Defaults to 100m.
        /// </summary>
        [Input("request_cpu")]
        public Input<string>? Request_cpu { get; set; }

        /// <summary>
        /// Requested memory. E.g. 64Mi means 64 MiB. Defaults to 64Mi.
        /// </summary>
        [Input("request_memory")]
        public Input<string>? Request_memory { get; set; }

        /// <summary>
        /// Target port for the service. Defaults to the containerPort.
        /// </summary>
        [Input("targetPort")]
        public Input<double>? TargetPort { get; set; }

        public ServiceDeploymentArgs()
        {
        }
        public static new ServiceDeploymentArgs Empty => new ServiceDeploymentArgs();
    }
}
