# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ServiceDeploymentArgs', 'ServiceDeployment']

@pulumi.input_type
class ServiceDeploymentArgs:
    def __init__(__self__, *,
                 container_port: pulumi.Input[float],
                 image: pulumi.Input[str],
                 namespace: pulumi.Input[str],
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 is_minikube: Optional[pulumi.Input[bool]] = None,
                 replicas: Optional[pulumi.Input[float]] = None,
                 request_cpu: Optional[pulumi.Input[str]] = None,
                 request_memory: Optional[pulumi.Input[str]] = None,
                 target_port: Optional[pulumi.Input[float]] = None):
        """
        The set of arguments for constructing a ServiceDeployment resource.
        :param pulumi.Input[float] container_port: Port container listens on.
        :param pulumi.Input[str] image: Name of the image for the application.
        :param pulumi.Input[str] namespace: K8s namespace to use.
        :param pulumi.Input[bool] allocate_ip_address: Whether or not to allocate an IP address for the service. Defaults to false.
        :param pulumi.Input[bool] is_minikube: Used to indicate if minikube environment is being used. Defaults to False.
        :param pulumi.Input[float] replicas: Number of pod replicas to create. Defaults to 1.
        :param pulumi.Input[str] request_cpu: Requested CPU. E.g. 250m means 0.25 CPU. Defaults to 100m.
        :param pulumi.Input[str] request_memory: Requested memory. E.g. 64Mi means 64 MiB. Defaults to 64Mi.
        :param pulumi.Input[float] target_port: Target port for the service. Defaults to the containerPort.
        """
        pulumi.set(__self__, "container_port", container_port)
        pulumi.set(__self__, "image", image)
        pulumi.set(__self__, "namespace", namespace)
        if allocate_ip_address is not None:
            pulumi.set(__self__, "allocate_ip_address", allocate_ip_address)
        if is_minikube is not None:
            pulumi.set(__self__, "is_minikube", is_minikube)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if request_cpu is not None:
            pulumi.set(__self__, "request_cpu", request_cpu)
        if request_memory is not None:
            pulumi.set(__self__, "request_memory", request_memory)
        if target_port is not None:
            pulumi.set(__self__, "target_port", target_port)

    @property
    @pulumi.getter(name="containerPort")
    def container_port(self) -> pulumi.Input[float]:
        """
        Port container listens on.
        """
        return pulumi.get(self, "container_port")

    @container_port.setter
    def container_port(self, value: pulumi.Input[float]):
        pulumi.set(self, "container_port", value)

    @property
    @pulumi.getter
    def image(self) -> pulumi.Input[str]:
        """
        Name of the image for the application.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: pulumi.Input[str]):
        pulumi.set(self, "image", value)

    @property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[str]:
        """
        K8s namespace to use.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[str]):
        pulumi.set(self, "namespace", value)

    @property
    @pulumi.getter(name="allocateIpAddress")
    def allocate_ip_address(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether or not to allocate an IP address for the service. Defaults to false.
        """
        return pulumi.get(self, "allocate_ip_address")

    @allocate_ip_address.setter
    def allocate_ip_address(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allocate_ip_address", value)

    @property
    @pulumi.getter(name="isMinikube")
    def is_minikube(self) -> Optional[pulumi.Input[bool]]:
        """
        Used to indicate if minikube environment is being used. Defaults to False.
        """
        return pulumi.get(self, "is_minikube")

    @is_minikube.setter
    def is_minikube(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_minikube", value)

    @property
    @pulumi.getter
    def replicas(self) -> Optional[pulumi.Input[float]]:
        """
        Number of pod replicas to create. Defaults to 1.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "replicas", value)

    @property
    @pulumi.getter
    def request_cpu(self) -> Optional[pulumi.Input[str]]:
        """
        Requested CPU. E.g. 250m means 0.25 CPU. Defaults to 100m.
        """
        return pulumi.get(self, "request_cpu")

    @request_cpu.setter
    def request_cpu(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "request_cpu", value)

    @property
    @pulumi.getter
    def request_memory(self) -> Optional[pulumi.Input[str]]:
        """
        Requested memory. E.g. 64Mi means 64 MiB. Defaults to 64Mi.
        """
        return pulumi.get(self, "request_memory")

    @request_memory.setter
    def request_memory(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "request_memory", value)

    @property
    @pulumi.getter(name="targetPort")
    def target_port(self) -> Optional[pulumi.Input[float]]:
        """
        Target port for the service. Defaults to the containerPort.
        """
        return pulumi.get(self, "target_port")

    @target_port.setter
    def target_port(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "target_port", value)


class ServiceDeployment(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 container_port: Optional[pulumi.Input[float]] = None,
                 image: Optional[pulumi.Input[str]] = None,
                 is_minikube: Optional[pulumi.Input[bool]] = None,
                 namespace: Optional[pulumi.Input[str]] = None,
                 replicas: Optional[pulumi.Input[float]] = None,
                 request_cpu: Optional[pulumi.Input[str]] = None,
                 request_memory: Optional[pulumi.Input[str]] = None,
                 target_port: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        """
        Create a ServiceDeployment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] allocate_ip_address: Whether or not to allocate an IP address for the service. Defaults to false.
        :param pulumi.Input[float] container_port: Port container listens on.
        :param pulumi.Input[str] image: Name of the image for the application.
        :param pulumi.Input[bool] is_minikube: Used to indicate if minikube environment is being used. Defaults to False.
        :param pulumi.Input[str] namespace: K8s namespace to use.
        :param pulumi.Input[float] replicas: Number of pod replicas to create. Defaults to 1.
        :param pulumi.Input[str] request_cpu: Requested CPU. E.g. 250m means 0.25 CPU. Defaults to 100m.
        :param pulumi.Input[str] request_memory: Requested memory. E.g. 64Mi means 64 MiB. Defaults to 64Mi.
        :param pulumi.Input[float] target_port: Target port for the service. Defaults to the containerPort.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceDeploymentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ServiceDeployment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ServiceDeploymentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceDeploymentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allocate_ip_address: Optional[pulumi.Input[bool]] = None,
                 container_port: Optional[pulumi.Input[float]] = None,
                 image: Optional[pulumi.Input[str]] = None,
                 is_minikube: Optional[pulumi.Input[bool]] = None,
                 namespace: Optional[pulumi.Input[str]] = None,
                 replicas: Optional[pulumi.Input[float]] = None,
                 request_cpu: Optional[pulumi.Input[str]] = None,
                 request_memory: Optional[pulumi.Input[str]] = None,
                 target_port: Optional[pulumi.Input[float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceDeploymentArgs.__new__(ServiceDeploymentArgs)

            __props__.__dict__["allocate_ip_address"] = allocate_ip_address
            if container_port is None and not opts.urn:
                raise TypeError("Missing required property 'container_port'")
            __props__.__dict__["container_port"] = container_port
            if image is None and not opts.urn:
                raise TypeError("Missing required property 'image'")
            __props__.__dict__["image"] = image
            __props__.__dict__["is_minikube"] = is_minikube
            if namespace is None and not opts.urn:
                raise TypeError("Missing required property 'namespace'")
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["request_cpu"] = request_cpu
            __props__.__dict__["request_memory"] = request_memory
            __props__.__dict__["target_port"] = target_port
            __props__.__dict__["ip_address"] = None
        super(ServiceDeployment, __self__).__init__(
            'k8sapp:index:ServiceDeployment',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> pulumi.Output[Optional[str]]:
        """
        Allocated IP address if applicable.
        """
        return pulumi.get(self, "ip_address")

