// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ServiceDeployment extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'k8sapp:index:ServiceDeployment';

    /**
     * Returns true if the given object is an instance of ServiceDeployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceDeployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceDeployment.__pulumiType;
    }

    /**
     * Allocated IP address if applicable.
     */
    public /*out*/ readonly ipAddress!: pulumi.Output<string | undefined>;

    /**
     * Create a ServiceDeployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceDeploymentArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.containerPort === undefined) && !opts.urn) {
                throw new Error("Missing required property 'containerPort'");
            }
            if ((!args || args.image === undefined) && !opts.urn) {
                throw new Error("Missing required property 'image'");
            }
            if ((!args || args.namespace === undefined) && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            resourceInputs["allocateIpAddress"] = args ? args.allocateIpAddress : undefined;
            resourceInputs["containerPort"] = args ? args.containerPort : undefined;
            resourceInputs["image"] = args ? args.image : undefined;
            resourceInputs["isMinikube"] = args ? args.isMinikube : undefined;
            resourceInputs["namespace"] = args ? args.namespace : undefined;
            resourceInputs["replicas"] = args ? args.replicas : undefined;
            resourceInputs["request_cpu"] = args ? args.request_cpu : undefined;
            resourceInputs["request_memory"] = args ? args.request_memory : undefined;
            resourceInputs["targetPort"] = args ? args.targetPort : undefined;
            resourceInputs["ipAddress"] = undefined /*out*/;
        } else {
            resourceInputs["ipAddress"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceDeployment.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ServiceDeployment resource.
 */
export interface ServiceDeploymentArgs {
    /**
     * Whether or not to allocate an IP address for the service. Defaults to false.
     */
    allocateIpAddress?: pulumi.Input<boolean>;
    /**
     * Port container listens on.
     */
    containerPort: pulumi.Input<number>;
    /**
     * Name of the image for the application.
     */
    image: pulumi.Input<string>;
    /**
     * Used to indicate if minikube environment is being used. Defaults to False.
     */
    isMinikube?: pulumi.Input<boolean>;
    /**
     * K8s namespace to use.
     */
    namespace: pulumi.Input<string>;
    /**
     * Number of pod replicas to create. Defaults to 1.
     */
    replicas?: pulumi.Input<number>;
    /**
     * Requested CPU. E.g. 250m means 0.25 CPU. Defaults to 100m.
     */
    request_cpu?: pulumi.Input<string>;
    /**
     * Requested memory. E.g. 64Mi means 64 MiB. Defaults to 64Mi.
     */
    request_memory?: pulumi.Input<string>;
    /**
     * Target port for the service. Defaults to the containerPort.
     */
    targetPort?: pulumi.Input<number>;
}
